version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
  test:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: ros --version
      - run: ros run -- --version

workflows:
  version: 2
  build_and_tes:
    jobs:
      - build
      - test
