version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - run: curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
      - run: ros run -q
