machine:
    environment:
        LISP: sbcl-bin
        PATH: ~/.roswell/bin:$PATH
        CXX: clang++

checkout:
    pre:
        - curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh

test:
    override:
        - ros --version
        - ros run -- --version
