version: 2
jobs:
  test:
    docker:
      - image: debian:stretch
    environment:
      - PATH: ~/roswel/bin:/usr/local/bin:$PATH
    steps:
      - checkout
      - run: apt install curl sh
      - run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - run: ros --version
      - run: ros run -- --version

workflows:
  version: 2
  build_and_tes:
    jobs:
      - test
